version: '3.3'
services:
  nginx:
    container_name: ${DC_CONTAINER_PREFIX}nginx.loc
    image: nginx:1.17-alpine
    volumes:
      - ${DC_BASE_DIR}nginx/config:/etc/nginx:ro
      - ${DC_BASE_DIR}nginx/certs:/etc/certs
      - ${DC_BASE_DIR}nginx/logs:/var/log/nginx
      - ${DC_BASE_DIR}app:/usr/share/nginx/html
    networks:
      internal:
        ipv4_address: ${IP_NGINX_CONTAINER}
    expose:
      - 80
      - 443
    links:
      - php
      - mysql
  php:
    container_name: ${DC_CONTAINER_PREFIX}php-fpm.loc
    build: ${DC_BASE_DIR}php
    volumes:
      - ${DC_BASE_DIR}php/config:/usr/local/etc:ro
      - ${DC_BASE_DIR}php/logs:/var/log
      - ${DC_BASE_DIR}app:/usr/share/nginx/html
    networks:
      internal:
        ipv4_address: ${IP_PHP_CONTAINER}
    ports:
      - 9000
    depends_on:
      - mysql
    links:
      - mysql
    tty: true
  mysql:
    container_name: ${DC_CONTAINER_PREFIX}mysql.loc
    build: ${DC_BASE_DIR}mysql
    volumes:
      - ${DC_BASE_DIR}mysql/config:/etc/my.cnf.external:ro
      - ${DC_BASE_DIR}mysql/logs:/var/log
      - mysql:/var/lib/mysql
    networks:
      internal:
        ipv4_address: ${IP_MYSQL_CONTAINER}
    ports:
      - 3306
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DEFAULT_DATABASE=${MYSQL_DEFAULT_DATABASE}
      - MYSQL_COLLATION=${MYSQL_COLLATION}
      - MYSQL_CHARSET=${MYSQL_CHARSET}
    tty: true
  sphinx:
    container_name: ${DC_CONTAINER_PREFIX}sphinx.loc
    build: ${DC_BASE_DIR}sphinx
    volumes:
      - ${DC_BASE_DIR}sphinx/config:/etc/sphinx/
      - sphinx:/var/lib/sphinx/data/
    networks:
      internal:
        ipv4_address: ${IP_SPHINX_CONTAINER}
    depends_on:
      - mysql
    links:
      - mysql
  #ToDo: memcached
  #ToDo: mail server
  #ToDo: (later, after other fixes) Redis, RabbitMQ etc
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: ${IP_SUBNET_MASK}
volumes:
  mysql:
  sphinx: